---
title: "Cost Modeling for WWTPs in Oregon"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE}
# Load packages
library(tidyverse)
library(tidymodels)
```

```{r output = FALSE, warning = FALSE, message = FALSE}
# Load data
dat <- read_csv("final_cost_small.csv")

dat <- dat %>%
    mutate(
    has_pumps = case_when(
      Collection %in% c("Conventional Gravity, Effluent Pumps",
                        "Effluent Pumps", "Effluent Pumps, Conventional Gravity",
                        "Conventional Gravity, Effluent Pumps, Small Diameter Gravity") ~ TRUE,
      Collection %in% c("Conventional Gravity", "-") ~ FALSE
    )
    ) %>%
  select(-X1, -X1_1) %>%
  mutate(
    pop_density = Population / sq_mi
  )
```

```{r}
# lm
m1 <- lm(log(`Total Cost`) ~ dryDesignFlowMGD + log(Population) + basic_treatment + Region + pop_density, data = dat)
summary(m1)

m2 <- lm(`Total Cost` ~ `Construction Cost`, data = dat)
summary(m2)$r.squared

m3 <- lm(log(`Total Cost`) ~ dryDesignFlowMGD + Region + pop_density, data = dat)
summary(m3)

m4 <- lm(log(`Total Cost`) ~ log(Population) + Region + pop_density, data = dat)
summary(m4)
```

```{r}
# Bayesian Modeling with {tidymodels} and {rstan}

## Set seed
set.seed(3737)

## Specify priors
prior_dist <- rstanarm::student_t(df = 1, location = 0)

## Create model
bayes_mod <-
  linear_reg() %>% 
  set_engine("stan", 
             prior_intercept = prior_dist, 
             prior = prior_dist) %>%
  translate()

## Fit model to data
bayes_fit <-
  bayes_mod %>%
  fit(log(`Total Cost`) ~ log(Population) + basic_treatment + dryDesignFlowMGD + pop_density + Region,
      data = dat)

## Extract fit results
# bayes_fit$fit
# bayes_fit$fit$coefficients
stan_fit <- bayes_fit$fit$stanfit
# class(stan_fit)
# stan_fit
# stan_fit@sim$samples[[4]]$`beta[4]`
bayes_fit

## Visualize dist for log(pop)
log_pop_dist_df <- data.frame(samples = c(stan_fit@sim$samples[[1]]$`beta[1]`,
                                          stan_fit@sim$samples[[2]]$`beta[1]`,
                                          stan_fit@sim$samples[[3]]$`beta[1]`,
                                          stan_fit@sim$samples[[4]]$`beta[1]`))
ggplot(log_pop_dist_df,
       aes(samples)) +
  stat_function(fun = dt, args = list(df = 1)) +
  stat_function(fun = dt, args = list(df = 1), geom = "area", aes(fill = "Prior"), alpha = 0.4) +
  scale_fill_manual(values = c("goldenrod", "steelblue")) +
  geom_density(aes(fill = "Posterior"), alpha = 0.4) +
  theme_bw() +
  xlim(-2,2)
```