---
title: "Data Visualizations and Analysis"
author: "Grayson White"
date: "7/13/2020"
output:
  #pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
# This script loads, cleans, and tidies the survey data and the osts/deq data. It then joins these two dataframes into
# a single dataframe called `working_df`. This dataframe includes variables from the survey data that I 
# considered to be key variables, but there are many more that could be included quite easily. 


setwd("~/dspg-wastewater")
# load necessary packages  --------------------------------------------------------------------------------------------
library(tidyverse)
library(readxl)

# loading in and cleaning the survey dataframes -----------------------------------------------------------------------
survey_2017 <- read_excel("data/raw/Water_Rates_Survey_2017.xlsx", 
                          sheet = "CLEANED")
colnames(survey_2017) <- survey_2017[1,]
survey_2017 <- survey_2017[-1,]

survey_2017_select <- survey_2017[, c(1, 36, 39, 42, 45, 48, 84,97, 157:199)]

colnames(survey_2017_select) <- c("City", "percent_rate_rev_to_debt", "percent_rate_rev_to_debt_NA", "assit_management_sys",
                                  "last_year_rate_study", "last_year_methodolgy_updates", "charge_for_ww_services",
                                  "5000_gal_bill", "provide_ww_service", "service_pop_residents_inside",
                                  "service_pop_residents_outside", "service_pop_peakseason_inside", "service_pop_peakseason_outside",
                                  "num_connections_res_inside", "num_connections_res_outside", "num_connections_comm_inside",
                                  "num_connections_comm_outside", "num_connections_other_inside", "num_connections_other_outside",
                                  "annual_vol_res_customer", "total_sewer_line_mi", "total_pumps_liftstations", "total_treatment_plants",
                                  "percent_combined_sewer", "treatment_level_primary", "treatment_level_secondary", "treatment_level_tertiary",
                                  "treatment_level_nitrogen_removal", "treatment_level_phosphorous_removal", "treatment_level_other",
                                  "treatment_level_other_text", "stream_water_TMDL", "explain_TMDL", "year_of_construction", "last_major_renovation",
                                  "capacity_dry_weather", "capacity_peak_wet_weather", "total_ww_treated_2016", "peak_wet_weather_flow_2016",
                                  "peak_dry_weather_flow_2016", "perc_capacity_operating_at", "year_at_max_capacity", "year_exceed_design_capacity",
                                  "indust_pretreatment", "reclaimed_water_public_private", "perc_reclaimed_is_reused_applied",
                                  "where_reuse", "biosolids_to_public_private", "perc_biosolids_applied", "where_biosolids",
                                  "additional_comments")
treatment_df <- survey_2017_select %>%
  select(treatment_level_primary, treatment_level_secondary, treatment_level_tertiary,
         treatment_level_nitrogen_removal, treatment_level_phosphorous_removal, treatment_level_other_text, City) 

treatment_df$treatment_level_primary <- str_replace_all(treatment_df$treatment_level_primary, "1", "Primary")
treatment_df$treatment_level_secondary <- str_replace_all(treatment_df$treatment_level_secondary, "1", "Secondary")
treatment_df$treatment_level_tertiary <- str_replace_all(treatment_df$treatment_level_tertiary, "1", "Tertiary")
treatment_df$treatment_level_nitrogen_removal <- str_replace_all(treatment_df$treatment_level_nitrogen_removal, "1", "Nitrogen Removal")
treatment_df$treatment_level_phosphorous_removal <- str_replace_all(treatment_df$treatment_level_phosphorous_removal, "1", "Phosphorous Removal")

treatment_df <- treatment_df %>%
  unite(level_of_treatment, treatment_level_primary, treatment_level_secondary, treatment_level_tertiary,
        treatment_level_nitrogen_removal, treatment_level_phosphorous_removal, treatment_level_other_text,
        sep = ", ", na.rm = TRUE)

survey_2017_select <- left_join(survey_2017_select, treatment_df)


survey_2017_select$`5000_gal_bill` <- parse_number(survey_2017_select$`5000_gal_bill`)
survey_2017_select$total_sewer_line_mi <- parse_number(survey_2017_select$total_sewer_line_mi)
survey_2017_select$year_of_construction <- parse_number(survey_2017_select$year_of_construction)
survey_2017_select$last_major_renovation <- parse_number(survey_2017_select$last_major_renovation)

# overwrites data file with file called `survey_2017` in your global environment
# saveRDS(survey_2017, "data/cleaned-and-or-rds/survey_2017.rds")


survey_2019 <- read_excel("data/raw/Water Rates Survey 2019_November 19, 2019_08.19.xlsx", 
                          sheet = "Cleaned")

survey_2019_select <- survey_2019[, c(1:4, 27,71, 137:162)] %>%
  rename(rev_debt_percent = "What percentage of rate revenue is obligated to debt services for the following systems? - Rate Revenue - Wastewater - %",
         "5000_gal_bill" = "For wastewater services, if you were to bill a residential customer for 5,000 gallons (6.684 CCFs) with a 3/4'' meter size, what dollar amount would you bill them, including the base rate?",
         annual_usage_per_customer = "What is the annual average wastewater base (volume) for a residential customer (x1000 gal. or 1.337 CCFs)?",
         total_sewer_lines_mi = "Please provide the following facility, lines, and treatment information: - Total miles of sewer lines (all sizes), not including service laterals",
         total_pumps_lift_stations = "Please provide the following facility, lines, and treatment information: - Total number of pumps and lift stations in your city",
         total_number_treatment_plants = "Please provide the following facility, lines, and treatment information: - Total number of treatment plants",
         combined_sewer_percentage = "Please provide the following facility, lines, and treatment information: - What percent of city wastewater lines also serve stormwater (i.e. combined sewer)?",
         level_of_treatment = "What level of wastewater treatment is provided to city wastewater (Check all that apply)? - Selected Choice",
         level_of_treatment_other = "What level of wastewater treatment is provided to city wastewater (Check all that apply)? - Other (Please Specify) - Text",
         year_of_contruction = "Please provide the following system age and capacity information: - Year of original plant construction completion",
         year_of_renovation = "Please provide the following system age and capacity information: - Year of last major plant update",
         design_capacity_dry_weather = "Please provide the following system age and capacity information: - What is the design capacity of your treatment plant(s) in dry weather (MGD)?",
         design_capacity_peak_wet_weather = "Please provide the following system age and capacity information: - What is the design capacity of your treatment plant(s) in peak wet weather (MGD)?",
         total_ww_treated = "Please provide the following system age and capacity information: - What is the total amount of wastewater treated in 2018 (MG)?",
         peak_wet_weather_flow = "Please provide the following system age and capacity information: - What was the peak wet weather flow in 2018 (MGD)?",
         peak_dry_weather_flow = "Please provide the following system age and capacity information: - What was the peak dry weather flow in 2018 (MGD)?",
         operating_capacity = "At what percent (%) capacity is the entire wastewater system operating?",
         year_at_max_capacity = "In what year will the wastewater system be at maximum capacity?",
         year_exceed_max_capacity = "In what year will your daily production exceed design capacity?...153",
         pre_treatment = "Does your city administer an industrial wastewater pre-treatment program?",
         reclaimed_water_to_public_private = "Does your city apply or provide reclaimed water to public/private property?",
         percentage_reclaimed_is_reused_applied = "What percentage (%) of total reclaimed water is reused/applied?",
         where_is_reuse = "Where does this reuse and application occur (i.e. city park, private golf course, industrial cooling tower, etc.)?",
         biosolids_to_public_private = "Does your city apply biosolids to public/ private property?",
         where_is_biosolids = "Where does this biosolid application occur (i.e. city park, private golf course, etc.)?",
         landfill_biosolids = "Does your city landfill biosolids?",
         percentage_biosolids_landfill = "What percentage (%) of biosolids are landfilled?",
         additional_comments = "Do you have any additional comments on wastewater services?")

survey_2019_select$`5000_gal_bill` <- parse_number(survey_2019_select$`5000_gal_bill`)
survey_2019_select$total_sewer_lines_mi <- parse_number(survey_2019_select$total_sewer_lines_mi)
survey_2019_select$year_of_contruction <- parse_number(survey_2019_select$year_of_contruction)
survey_2019_select$year_of_renovation <- parse_number(survey_2019_select$year_of_renovation)

# overwrites data file with file called `survey_2019` in your global environment
# saveRDS(survey_2019, "data/cleaned-and-or-rds/survey_2019.rds")

# end of loading and tidying survey data -------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Heavily reducing number of columns to key vars, merging 2017 and 2019, -----------------------------------------------
# merging those the the `osts` dataset ---------------------------------------------------------------------------------

survey_2019_key_vars <- survey_2019_select %>%
  select(City, Population, QCODE, Region, `5000_gal_bill`, total_sewer_lines_mi,
         year_of_contruction, year_of_renovation, total_ww_treated, level_of_treatment,
         level_of_treatment_other) %>%
  rename(`5000_gal_bill_2019` = `5000_gal_bill`,
         total_sewer_lines_mi_2019 = total_sewer_lines_mi,
         year_of_construction_2019 = year_of_contruction,
         year_of_renovation_2019 = year_of_renovation,
         total_ww_treated_2019 = total_ww_treated,
         level_of_treatment_2019 = level_of_treatment)

survey_2017_key_vars <- survey_2017_select %>%
  select(City, `5000_gal_bill`, total_sewer_line_mi, year_of_construction, last_major_renovation,
         total_ww_treated_2016, level_of_treatment) %>%
  rename(`5000_gal_bill_2017` = `5000_gal_bill`,
         total_sewer_lines_mi_2017 = total_sewer_line_mi,
         year_of_construction_2017 = year_of_construction,
         year_of_renovation_2017 = last_major_renovation,
         total_ww_treated_2017 = total_ww_treated_2016,
         level_of_treatment_2017 = level_of_treatment)

key_survey_vars <- full_join(survey_2017_key_vars, survey_2019_key_vars,
                             by = c("City" = "City"))
  # load in osts dataset -----------------------------------------------
osts_municipalities <- read_excel("data/christine-google-drive-data/Oregon Sewage Treatment Systems.xlsx", 
                                  sheet = "Municipalities")

osts_non_municipalities <- read_excel("data/christine-google-drive-data/Oregon Sewage Treatment Systems.xlsx", 
                                      sheet = "non municipalities")

osts_municipalities <- osts_municipalities %>%
  mutate(municipality = "yes")

osts_non_municipalities <- osts_non_municipalities %>%
  mutate(municipality = "no")

osts <- full_join(osts_municipalities, osts_non_municipalities)

osts <- osts %>%
  filter(Flow %in% c("<1 MGD with lagoons", "< 1MGD"))

  # complete join -------------------------------------------------------
working_df <- left_join(osts, key_survey_vars,
                     by = c("City" = "City")) %>%
  unite(`5000_gal_bill`, c(`5000_gal_bill_2017`, `5000_gal_bill_2019`), remove = TRUE, na.rm = TRUE) %>%
  unite(total_sewer_lines_mi, c(total_sewer_lines_mi_2017, total_sewer_lines_mi_2019), remove = TRUE, na.rm = TRUE) %>%
  unite(year_of_construction, c(year_of_construction_2017, year_of_construction_2019), remove = TRUE, na.rm = TRUE) %>%
  unite(year_of_renovation, c(year_of_renovation_2017, year_of_renovation_2019), remove = TRUE, na.rm = TRUE) %>%
  unite(total_ww_treated, c(total_ww_treated_2017, total_ww_treated_2019), remove = TRUE, na.rm = TRUE) %>%
  unite(level_of_treatment, c(level_of_treatment_2017, level_of_treatment_2019), sep = "_____", remove = TRUE, na.rm = TRUE)


  # add population data --------------------------------------------------
pop <- read.csv("data/raw/or_pop_by_decade.csv")
pop <- pop[-(1:3),]
colnames(pop) <- c("City", "pop_2018", "pop_2010", "pop_2000", "pop_1990", "pop_1980")
rownames(pop) <- NULL


working_df <- working_df %>%
  left_join(pop, by = c("City" = "City"))

  # add acreage
acres <- read.csv("data/raw/city_limits.csv") %>%
  select(CITY_NAME, acres) %>%
  rename(City = CITY_NAME)

working_df <- working_df %>%
  left_join(acres, by = c("City" = "City"))


# Merge data with Amanda's permit data ----------------------------------------------------------------------------------
Permits <- read_csv("data/raw/Permits.csv")

Permits <- Permits %>%
  select(-`phone#`, -firstname, -lastname, -constructionYear)

working_df <- working_df %>%
  left_join(Permits)


# Remove observations that Christine flagged ----------------------------------------------------------------------------
remove <- read_csv("data/raw/remove.csv")
working_df <- working_df %>%
  anti_join(remove) %>%
  filter(municipality == "yes")

# Remove duplicate observation ------------------------------------------------------------------------------------------
working_df <- working_df[-104,]

# Add relevant columns for cost data collection -------------------------------------------------------------------------
working_df <- working_df %>%
  add_column(upgrade1 = NA) %>%
  add_column(upgrade1_cost = NA) %>%
  add_column(upgrade1_year = NA) %>%
  add_column(upgrade2 = NA) %>%
  add_column(upgrade2_cost = NA) %>%
  add_column(upgrade2_year = NA) %>%
  add_column(upgrade3 = NA) %>%
  add_column(upgrade3_cost = NA) %>%
  add_column(upgrade3_year = NA) %>%
  add_column(cap_cost = NA) %>%
  add_column(om_cost = NA)

# Misc Data cleaning ----------------------------------------------------------------------------------------------------
working_df$pop_2018 <- parse_number(working_df$pop_2018) 
working_df$pop_2010 <- parse_number(working_df$pop_2010)
working_df$pop_2000 <- parse_number(working_df$pop_2000)
working_df$pop_1990 <- parse_number(working_df$pop_1990) 
working_df$pop_1980 <- parse_number(working_df$pop_1980)

working_df <- working_df %>%
  mutate(
    sq_mi = acres / 640,
    pop_density_2018 = pop_2018 / sq_mi
  )


# Merge cost data from USDA ---------------------------------------------------------------------------------------------
usda_cost <- read_excel("data/raw/wastewater-projects.xlsx")

usda_cost$Entity <- sapply(usda_cost$Entity, toupper)
usda_cost$Entity[15] <- "PACIFIC CITY JOINT WATER-SANITARY AUTHORITY"

cost <- usda_cost %>%
  left_join(working_df,
             by = c("Entity" = "Legal_Name"))

cost <- cost %>%
  filter(!is.na(Flow))
```


```{r}
ggplot(working_df, aes(x = log(pop_2018), y = dryDesignFlowMGD)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() +
  labs(x = "Log of Population (2018)")
```

```{r}
ggplot(working_df, aes(x = log(pop_2018),
                       y = parse_number(`TSS monthly average lbs/day`))) +
  geom_point() +
  theme_bw()
```

```{r}
working_df %>%
  filter(type1 %in% c("lagoons", "activated sludge")) %>%
  group_by(type1) %>%
  summarize(median = median(pop_2018, na.rm = TRUE))
```

```{r}
library(viridis)
library(plotly)
p <- working_df %>%
  ggplot(aes(x = Region.x,
             fill = type1)) +
  geom_bar(position = "fill") +
  scale_fill_viridis_d(option = "C", na.value = "grey50") +
  scale_x_discrete(labels=c("Eastern", "Northwest", "West")) +
  theme_bw() +
  labs(x = "Region",
       fill = "Main Type",
       y = "Proportion",
       title = "Rural WWTPs in Oregon by Type")
p
# ggplotly(p, tooltip = c("type1", "count"))

working_df %>%
  filter(type2 != c("na", NA)) %>%
  ggplot(aes(x = Region.x,
             fill = type2)) +
  geom_bar(position = "fill") +
  scale_fill_viridis_d(option = "C", na.value = "grey50") +
  scale_x_discrete(labels=c("Eastern", "Northwest", "West")) +
  theme_bw() +
  labs(x = "Region",
       fill = "Secondary Type",
       y = "Proportion",
       title = "Rural WWTPs in Oregon by Secondary Type")

library(LaCroixColoR)

p4 <- working_df %>%
  mutate(
    type_plot = case_when(
      type1 %in% c("lagoons", "pre-aerated lagoons") ~ "lagoons",
      type1 %in% c("trickling filter", "trickling filter - high rate",
                   "trickling filter - low rate") ~ "trickling filter",
      type1 %in% c("activated sludge") ~ "activated sludge",
      type1 %in% c("extended aeration", "membrane bioreactor", "recirculating gravel filter", NA,
                   "STEP system", "oxidation ditch", "biological contactors"
    ) ~ "other"
  )) %>%
  ggplot(aes(x = Region.x,
             fill = factor(type_plot, levels = c("activated sludge", "lagoons", "trickling filter", "other")))) +
  geom_bar(position = "fill") +
  scale_fill_manual(values = lacroix_palette("Pamplemousse", type = "discrete")) +
  scale_x_discrete(labels=c("Eastern", "Northwest", "West")) +
  theme_bw() +
  labs(x = "Region",
       fill = "Type",
       y = "Proportion",
       title = "Rural WWTPs in Oregon by Type and DEQ Region") 
  #theme(legend.position = "bottom")
p4
```

```{r}
library(gtools)
working_df$quantile_density <- quantcut(working_df$pop_density_2018, q = 4)
ggplot(working_df[!is.na(working_df$quantile_density), ], aes(x = quantile_density,
                       fill = type1)) +
  geom_bar(position = "fill") +
  scale_x_discrete(labels=c("Up to 1050", "1050 to 1660", "1660 to 2350", "2350 and more")) +
  scale_fill_viridis_d(option = "B", na.value = "grey50") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Population Density (People / Square Mile)",
       y = "Proportion",
       fill = "Type",
       title = "Types of WWTPs Grouped By Population Density")


working_df$quantile_pop_2018 <- quantcut(working_df$pop_2018, q = 4)
working_df$cut_pop_2018 <- cut(working_df$pop_2018, breaks = c(0, 2500, 5000, 10000, 1e7))
p1 <- ggplot(working_df[!is.na(working_df$cut_pop_2018), ], aes(x = cut_pop_2018,
                       fill = type1)) +
  geom_bar(position = "fill") +
  scale_x_discrete(labels=c("Up to 2500", "2500 to 5000", "5000 to 10000", "10000 and more")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  labs(x = "Population (2018)",
       y = "Proportion",
       title = "Type of WWTP Grouped by Population",
       fill = "Type")

p1

# ggplotly(p1)

```


Maps:
```{r}
library(sf)
library(USAboundaries)
library(PNWColors)
df_sf <- st_as_sf(working_df, coords = c("Longitude", "Latitude"), crs = "+proj=longlat +datum=WGS84")
OR_sf <- us_boundaries(type = "state", states = "OR")


working_df_ <- working_df %>%
  filter(dryDesignFlowMGD <= 1)
p2 <- ggplot() +
  geom_sf(data = OR_sf, fill = "#009474") +
  geom_point(data = working_df_,
             aes(
                 x = Longitude,
                 y = Latitude,
                 size = dryDesignFlowMGD
                 ),
             alpha = 0.6,
             color = "#15266B") +
  coord_sf() +
  theme_void() +
  labs(title = "Small (<1 MGD) Wastewater Treatment Facilities in Oregon",
       size = "Dry Design Flow (MGD)") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.title.position = "plot",
        legend.position = "bottom")

p2
```



```{r}
# pop la croix
working_df <- working_df %>%
  mutate(
    type_plot = case_when(
      type1 %in% c("lagoons", "pre-aerated lagoons") ~ "lagoons",
      type1 %in% c("trickling filter", "trickling filter - high rate",
                   "trickling filter - low rate") ~ "trickling filter",
      type1 %in% c("activated sludge") ~ "activated sludge",
      type1 %in% c("extended aeration", "membrane bioreactor", "recirculating gravel filter", NA,
                   "STEP system", "oxidation ditch", "biological contactors"
    ) ~ "other/NA"
  ))
ggplot(working_df[!is.na(working_df$cut_pop_2018), ], aes(x = cut_pop_2018,
                       fill = factor(type_plot, levels = c("activated sludge", "lagoons", "trickling filter", "other/NA")))) +
  geom_bar(position = "fill") +
  scale_x_discrete(labels=c("Up to 2500", "2500 to 5000", "5000 to 10000", "10000 and more")) +
  scale_fill_viridis_d(option = "E") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1),
        legend.position = "bottom") +
  labs(x = "Population (2018)",
       y = "Proportion",
       title = "Type of WWTP Grouped by Population",
       fill = "Type") 
```


```{r}
# do not run, does not work, crashes R
# try pop densities
# library(tidycensus)
# library(tigris)
# 
# pop_block <- get_acs(
#   geography = "block group",
#   variables = "B01003_001",
#   state = "OR",
#   geometry = TRUE,
#   key = "abac0e1ca2aa3d3ebb31d6d2fcdbaf52d3e25f7d"
# )
# 
# area_2017 <-
#   block_groups(year = 2017,
#                state = "OR",
#                class = "sf")
# 
# area_2017 <- area_2017 %>%
#   mutate(area = ALAND / 2589988) %>%
#   select(area, geometry, GEOID)
# 
# pop_block <- pop_block %>%
#   select(estimate, geometry, GEOID)
# 
# class(pop_block) <- "data.frame"
# class(area_2017) <- "data.frame"
#     
# density <- left_join(pop_block, area_2017, by = c("GEOID" = "GEOID"))
# 
# density <- density %>%
#   mutate(pop_density = estimate/area)
# 
# class(density) <- c("sf", "data.frame")
```


```{r}
working_df %>%
  ggplot(aes(x = pop_density_2018)) +
  geom_density(fill = "#EBBDCB",
               alpha = 0.5) +
  theme_bw() +
  labs(x = "Population Density (2018)",
       title = "Population Density of Towns/Cities in Our Sample")

working_df %>%
  ggplot(aes(x = pop_density_2018)) +
  geom_histogram(bins = 11,
                 fill = "#EBBDCB",
                 color = "grey30") +
  theme_bw() +
  labs(x = "Population Density in 2018 (people/square mile)",
       title = "Population Density of Towns/Cities in Our Sample")
```

```{r}
working_df %>%
  filter(!is.na(basin)) %>%
  group_by(basin) %>%
  summarize(mgd = mean(dryDesignFlowMGD, na.rm = TRUE)) %>%
  ggplot(
    aes(x = reorder(basin, mgd), y = mgd)
  ) +
  geom_col(fill = "maroon") +
  coord_flip() +
  theme_bw() +
  labs(
    x = "Average Dry Design Flow (MGD)",
    y = "Basin",
    title = "Average Dry Design Flow, Grouped By Basin"
  )
```

```{r}
# cost
cost %>%
  ggplot(aes(x = log(`Total Cost`),
             y = pop_2018)) +
  geom_point() +
  theme_bw()

cost %>%
  ggplot(aes(x = log(`Total Cost`),
             y = dryDesignFlowMGD)) +
  geom_point() +
  theme_bw()

cost %>%
  ggplot(aes(x = log(`Total Cost`),
             y = pop_density_2018)) +
  geom_point() +
  theme_bw()

m1 <- lm(log(`Total Cost`) ~ dryDesignFlowMGD + pop_2018 + pop_density_2018 + Region.x, data = cost)
summary(m1)

library(scales)
point <- format_format(big.mark = ",", decimal.mark = ".", scientific = FALSE)
cost %>%
  ggplot(aes(x = type1,
             y = mean(`Total Cost`))) +
  geom_col(fill = "forest green") +
  labs(x = "Type of WWTP",
       y = "Average Total Cost ($)") +
  theme_bw() +
  scale_y_continuous(labels = point)

cost %>%
  group_by(type1) %>%
  summarize(n())

```

```{r}
head(usda_cost)
```

```{r}

usda_cost %>%
  ggplot(aes(x = `Total Cost`)) +
  geom_histogram(binwidth = 3000000) + 
  theme_bw()

usda_cost %>%
  ggplot(aes(x = log(`Total Cost`))) +
  geom_histogram(binwidth = 0.5) + 
  theme_bw()

usda_cost %>%
  ggplot(aes(x = Population,
             y = `Total Cost`)) +
  geom_point() + 
  theme_bw()

usda_cost %>%
  ggplot(aes(x = log(Population),
             y = log(`Total Cost`))) +
  geom_point() + 
  theme_bw()

usda_cost %>%
  ggplot(aes(x = log(Population),
             y = log(`Total Cost`))) +
  stat_smooth(method = "lm") +
  geom_point() + 
  theme_bw()

```

```{r}
mod <- lm(log(`Total Cost`) ~ log(Population), data = usda_cost)
summary(mod)
plot(mod)
```

