---
title: "modeling"
author: "Grayson White"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r output = FALSE, warning = FALSE, message = FALSE}
# Load packages
library(tidyverse)
library(tidymodels)
library(priceR)
```

```{r output = FALSE, warning = FALSE, message = FALSE}
# Load data
dat <- read_csv("dat.csv")
```

This document will preform both frequentist and bayesian methods, comparing the outcomes of the two. We will also use both standard functions such as `lm()` from the built-in `stats` package, and we will also perform our analyses with `tidymodels` packages.

# Frequentist, `stats` package
```{r}
# Model experimentation
m1 <- lm(log(`Total Cost`) ~ dryDesignFlowMGD + log(Population) + basic_treatment + Region + pop_density,
         data = dat)
summary(m1)

m2 <- lm(log(`Total Cost`) ~ log(Population) + Region + pop_density,
         data = dat)
summary(m2)

m2_inf <- lm(log(total_cost) ~ log(Population) + log(pop_density) + basic_treatment + has_pumps,
         data = dat)
summary(m2_inf)

m3 <- lm(log(`Total Cost`) ~ massLoadFlowMGD + Region + pop_density + coastal,
         data = dat)
summary(m3)

dat_filtered <- dat %>%
  filter(type1 %in% c("lagoons", "activated sludge"))

m4 <- lm(log(`Total Cost`) ~ log(Population) + Region + pop_density + type1,
         data = dat_filtered)
summary(m4)


m5 <- lm(log(total_cost) ~ log(Population) + Region + pop_density + basic_treatment + `Permit Type`,
         data = dat)
summary(m5)
```

```{r}
# Final model specification
final_model <- lm(log(total_cost) ~ log(Population) + log(pop_density) + basic_treatment + has_pumps,
         data = dat)
summary(final_model)
```


# Bayesian, `tidymodels` and `rstan` packages
```{r}
## Set seed
set.seed(3737)

## Specify priors
prior_dist <- c(
  rstanarm::normal(location = c(0.5), scale = c(0.25)),
  rstanarm::normal(location = c(-0.5), scale = c(0.5)),
  rstanarm::normal(location = c(0), scale = c(1)),
  rstanarm::normal(location = c(0), scale = c(1)),
  rstanarm::normal(location = c(0), scale = c(1))
  )

## Create model
bayes_mod <-
  linear_reg() %>% 
  set_engine("stan", 
             prior_intercept = rstanarm::normal(), 
             prior = prior_dist) %>%
  translate()

## Fit model to data
bayes_fit <-
  bayes_mod %>%
  fit(log(total_cost) ~ log(Population) + log(pop_density) + basic_treatment + has_pumps,
      data = dat)

## Extract fit results
# bayes_fit$fit
# bayes_fit$fit$coefficients
stan_fit <- bayes_fit$fit$stanfit
# class(stan_fit)
# stan_fit
# stan_fit@sim$samples[[4]]$`beta[4]`
bayes_fit

## Visualize dist for log(pop)
log_pop_dist_df <- data.frame(samples = c(stan_fit@sim$samples[[1]]$`beta[1]`,
                                          stan_fit@sim$samples[[2]]$`beta[1]`,
                                          stan_fit@sim$samples[[3]]$`beta[1]`,
                                          stan_fit@sim$samples[[4]]$`beta[1]`))
ggplot(log_pop_dist_df,
       aes(samples)) +
  stat_function(fun = dnorm, args = list(mean = 0.5, sd = 0.25)) +
  stat_function(fun = dnorm, args = list(mean = 0.5, sd = 0.25), geom = "area", aes(fill = "Prior"), alpha = 0.4) +
  scale_fill_manual(values = c("goldenrod", "steelblue")) +
  geom_density(aes(fill = "Posterior"), alpha = 0.4) +
  theme_bw() +
  xlim(-2,2)
```



